import assets from '../assets';

export const Data = {
  productItems: [
    {
      id: 1,
      discount: 0,
      cover: assets.images.flash.flash1,
      name: 'Chaussures',
      price: 100,
      rating: 4,
    },
    {
      id: 2,
      discount: 50,
      cover: assets.images.flash.flash2,
      name: 'Montre',
      price: 20,
      rating: 5,
    },
    {
      id: 3,
      discount: 0,
      cover: assets.images.flash.flash3,
      name: 'Smartphone Noir',
      price: 200,
      rating: 3.5,
    },
    {
      id: 4,
      discount: 0,
      cover: assets.images.flash.flash4,
      name: 'Montre Connectée Noire',
      price: 25,
      rating: 4.5,
    },
    {
      id: 5,
      discount: 13,
      cover: assets.images.flash.flash5,
      name: 'Lunettes',
      price: 100,
      rating: 4,
    },
    {
      id: 6,
      discount: 0,
      cover: assets.images.flash.flash1,
      name: 'Chaussures',
      price: 100,
      rating: 4,
    },
  ],
  allProducts: [
    {
      id: 1,
      discount: 0,
      cover: assets.images.flash.flash1,
      name: 'Chaussures',
      price: 100,
      rating: 4,
    },
    {
      id: 2,
      discount: 50,
      cover: assets.images.flash.flash2,
      name: 'Montre',
      price: 20,
      rating: 5,
    },
    {
      id: 3,
      discount: 0,
      cover: assets.images.flash.flash3,
      name: 'Smartphone Noir',
      price: 200,
      rating: 3.5,
    },
    {
      id: 4,
      discount: 0,
      cover: assets.images.flash.flash4,
      name: 'Montre Connectée Noire',
      price: 25,
      rating: 4.5,
    },
    {
      id: 5,
      discount: 13,
      cover: assets.images.flash.flash5,
      name: 'Chaussures',
      price: 100,
      rating: 4,
    },
    {
      id: 6,
      discount: 0,
      cover: assets.images.flash.flash1,
      name: 'Chaussures',
      price: 100,
      rating: 4,
    },
    {
      id: 7,
      discount: 0,
      cover: assets.images.shops.shop1,
      name: 'Casque',
      price: 100,
      rating: 4,
    },
    {
      id: 8,
      discount: 0,
      cover: assets.images.shops.shop2,
      name: 'Mobile',
      rating: 4,
    },
    {
      id: 9,
      discount: 4,
      cover: assets.images.shops.shop3,
      name: 'Mobile',
      rating: 5,
    },
    {
      id: 10,
      discount: 10,
      cover: assets.images.shops.shop4,
      name: 'Mobile',
      rating: 2.5,
    },
    {
      id: 11,
      discount: 0,
      cover: assets.images.shops.shop5,
      name: 'Casque',
      rating: 4,
    },
    {
      id: 12,
      discount: 0,
      cover: assets.images.shops.shop6,
      name: 'Casque',
      rating: 2,
    },
    {
      id: 13,
      discount: 0,
      cover: assets.images.shops.shop7,
      name: 'Téléphone',
      rating: 4,
    },
    {
      id: 14,
      discount: 0,
      cover: assets.images.shops.shop8,
      name: 'Casque',
      rating: 5,
    },
    {
      id: 15,
      discount: 0,
      cover: assets.images.shops.shop9,
      name: 'Casque',
      rating: 1.5,
    },
    {
      id: 16,
      discount: 0,
      cover: assets.images.shops.shop10,
      name: 'Casquette',
      rating: 3.7,
    },
  ],
};
